from enum import Enum


class EnglishSourceData(str, Enum):
    word_formation_50 = "50 Word Formation (engxam.com)"
    word_formation_51 = "51 Word Formation (engxam.com)"
    word_formation_52 = "52 Word Formation (engxam.com)"
    word_formation_53 = "53 Word Formation (engxam.com)"
    word_formation_54 = "54 Word Formation (engxam.com)"
    word_formation_55 = "55 Word Formation (engxam.com)"
    word_formation_56 = "56 Word Formation (engxam.com)"
    word_formation_57 = "57 Word Formation (engxam.com)"
    word_formation_58 = "58 Word Formation (engxam.com)"
    word_formation_59 = "59 Word Formation (engxam.com)"
    all_about_the_usa = "All About the USA (A Cultural Reader)"
    cae_engexam_info = "CAE (engexam.info)"
    cae_50_kwt_vol_3 = "CAE 50 KWT vol. 3"
    cae_kwt = "CAE KWT"
    cae_kwt_vol_1 = "CAE KWT vol. 1"
    cambridge_advanced_key_word_transformation = "Cambridge Advanced Key Word Transformation"
    check_your_english_vocabulary_for_ielts = "Check Your English Vocabulary for IELTS"
    check_your_english_vocabulary_for_living_in_the_uki = "Check Your English Vocabulary for Living in the UKI"
    english_vocabulary_in_use_advanced = "English Vocabulary in Use Advanced"
    fce = "FCE (engexam.info)"
    fce_part_1 = "FCE, part 1"
    fce_part_2 = "FCE, part 2"
    fce_part_3 = "FCE, part 3"
    fce_part_4 = "FCE, part 4"
    fce_part_5 = "FCE, part 5"
    fce_part_6 = "FCE, part 6"
    fce_part_7 = "FCE, part 7"
    fce_part_8 = "FCE, part 8"
    fce_part_9 = "FCE, part 9"
    gold_advanced = "Gold Advanced"
    key_to_success = "Key to Success"
    reading_part_8 = "Reading Part 8 (10 texts) - Succeed in Advanced"
    trios = "TRIOS"
    the_lighter_side_of_tefl = "The Lighter Side of TEFL"
    vsosh_mun = "ВсОШ (муниципальный этап)"
    vsosh_reg = "ВсОШ (региональный этап)"
    darya_bochkareva = "Дарья Бочкарева: Country Studies"
    kfu = "КФУ (перечневая, 11, 2019/2020)"
